// admin_audit_log'daki eylem kodlarının Türkçe karşılıkları. Önceden
// AdminPanel.tsx içinde ("Okullar & Duyuru" bölümündeki "Son işlemler"
// kartı) tanımlıydı — Faz 3 (2026-08-26) ile bu kart ayrı bir "İşlem
// Geçmişi" bölümüne taşındığı için paylaşılan bir yere alındı.
export const EYLEM_ETIKET: Record<string, string> = {
  sinif_ekle: "Sınıf eklendi",
  ogretmen_ekle_manuel: "Öğretmen eklendi",
  mudur_ekle_manuel: "Müdür eklendi",
  admin_duyuru_gonder: "Duyuru gönderildi",
  admin_duyuru_kaldir: "Yönetici duyurusu kaldırıldı",
  ogretmen_duyuru_gonder: "Duyuru gönderildi (öğretmen)",
  mudur_duyuru_gonder: "Duyuru gönderildi (müdür)",
  rehber_mesaj_gonder: "Rehberlik mesajı gönderildi",
  ogrenci_ekle_manuel: "Öğrenci eklendi",
  ogrenci_toplu_ekle: "Öğrenciler toplu eklendi",
  deneme_toplu_gir: "Deneme sonuçları toplu girildi",
  deneme_bildirim_gonder: "Deneme sonucu bildirimleri gönderildi",
  sinif_ogretmeni_ata: "Sınıf öğretmeni atandı",
  sinif_ogretmenliginden_cikar: "Sınıf öğretmenliğinden çıkarıldı",
  okul_ekle: "Okul eklendi",
  okul_duzenle: "Okul düzenlendi",
  okul_aktiflestir: "Okul aktifleştirildi",
  okul_pasiflestir: "Okul pasifleştirildi",
  sifre_sifirla: "Şifre sıfırlandı",
  sifre_belirle: "Şifre belirlendi",
  hesap_aktiflestir: "Hesap aktifleştirildi",
  hesap_pasiflestir: "Hesap pasifleştirildi",
  hesap_sil: "Kullanıcı kalıcı olarak silindi",
  kullanici_profil_guncelle: "Kullanıcı profili güncellendi",
  kullanici_kurum_degistir: "Kullanıcının okulu değiştirildi",
  kullanici_rolu_degistir: "Kullanıcının rolü değiştirildi",
  veli_ogrenci_bagla: "Veli öğrenciye bağlandı",
  veli_ogrenci_baglantisi_sil: "Veli–öğrenci bağlantısı silindi",
  ogrenci_kaydi_guncelle: "Öğrenci kaydı güncellendi",
  ogrenci_kaydi_sil: "Öğrenci kaydı silindi",
  sinif_sil: "Sınıf silindi",
  ogrenci_sinif_tasi: "Öğrenci sınıf değiştirdi",
  ogretmen_brans_degistir: "Öğretmen branşı değiştirildi",
  veli_talebi_admin_onayla: "Veli talebi onaylandı (admin)",
  veli_talebi_reddet: "Veli talebi reddedildi",
  konu_anlatimi_duzenle: "Konu anlatımı düzenlendi",
  konu_anlatimi_yeniden_uret: "Konu anlatımı yeniden üretildi",
  kurallar_metni_guncelle: "Kayıt kuralları metni güncellendi",
  izinli_ogrenci_listesi_yukle: "İzinli öğrenci listesi güncellendi",
  izinli_ogrenci_sil: "İzinli öğrenci listesinden silindi",
  izinli_ogrenci_listesi_temizle: "İzinli öğrenci listesi temizlendi",
  dershane_deneme_suresi_ayarla: "Dershane deneme süresi ayarlandı",
  site_bakima_al: "Site bakıma alındı",
  site_ac: "Site tekrar açıldı",
  admin_hesap_olustur: "Yeni yönetici hesabı oluşturuldu",
  moderatorluk_ver: "Moderatörlük yetkisi verildi",
  moderatorluk_al: "Moderatörlük yetkisi kaldırıldı",
  moderator_ogretmen_ekle: "Öğretmen eklendi (moderatör)",
  moderator_ogrenci_ekle: "Öğrenci eklendi (moderatör)",
  moderator_kurum_duzenle: "Kurum bilgileri düzenlendi (moderatör)",
  moderator_sifre_belirle: "Şifre belirlendi (moderatör)",
  moderator_sifre_sifirla: "Şifre sıfırlandı (moderatör)",
  moderator_rozet_sifirla: "Rozetler sıfırlandı (moderatör)",
  moderator_ogrenci_sinif_tasi: "Öğrenci sınıf değiştirdi (moderatör)",
  moderator_ogretmen_brans_degistir: "Öğretmen branşı değiştirildi (moderatör)",
  moderator_hesap_aktiflestir: "Hesap aktifleştirildi (moderatör)",
  moderator_hesap_pasiflestir: "Hesap pasifleştirildi (moderatör)",
  moderator_hesap_sil: "Kullanıcı silindi (moderatör)",
  moderator_yurt_ogrencisi_isaretle: "Yurt öğrencisi işaretlendi (moderatör)",
  moderator_yurt_ogrencisi_kaldir: "Yurt öğrencisi işareti kaldırıldı (moderatör)",
};
