"use client";
import {useMemo,useState,useTransition} from "react";
import {CalendarPlus,Music,Trash2,UserMinus,UserPlus,Users} from "lucide-react";
import {etkinlikCalismasiEkle,etkinlikGrubuEkle,etkinlikGrubuSil,etkinlikKarariVer,etkinlikUyesiDegistir} from "@/app/dashboard/etkinlik-actions";
import type {EtkinlikAtamasi,EtkinlikGrubu,EtkinlikOgrencisi} from "@/lib/etkinlik";
import {BG0,BG1,BG1_ALT,BLUSH,BORDER,BORDER_STRONG,MINT,MINT_ON,TEXT,TEXT_MUTED} from "@/lib/theme";

const inputStyle={background:BG0,color:TEXT,border:`2px solid ${BORDER_STRONG}`};
export function EtkinlikPaneli({mod,brans,siniflar,ogrenciler,gruplar,atamalar}:{mod:"ogretmen"|"ogrenci";brans?:string;siniflar?:{id:string;ad:string}[];ogrenciler?:EtkinlikOgrencisi[];gruplar?:EtkinlikGrubu[];atamalar?:EtkinlikAtamasi[]}){
 const [pending,start]=useTransition(),[mesaj,setMesaj]=useState<string|null>(null);const calistir=(f:()=>Promise<{error:string|null}>)=>start(async()=>{setMesaj(null);const r=await f();if(r.error)setMesaj(r.error);else location.reload();});
 if(mod==="ogrenci")return <OgrenciEtkinlikleri atamalar={atamalar??[]} pending={pending} calistir={calistir} mesaj={mesaj}/>;
 return <OgretmenEtkinlikleri brans={brans??""} siniflar={siniflar??[]} ogrenciler={ogrenciler??[]} gruplar={gruplar??[]} pending={pending} calistir={calistir} mesaj={mesaj}/>;
}
function OgretmenEtkinlikleri({brans,siniflar,ogrenciler,gruplar,pending,calistir,mesaj}:{brans:string;siniflar:{id:string;ad:string}[];ogrenciler:EtkinlikOgrencisi[];gruplar:EtkinlikGrubu[];pending:boolean;calistir:(f:()=>Promise<{error:string|null}>)=>void;mesaj:string|null}){
 const [isim,setIsim]=useState(""),[sinif,setSinif]=useState(siniflar[0]?.id??""),[grup,setGrup]=useState(gruplar[0]?.id??"");const filtre=useMemo(()=>ogrenciler.filter(o=>!sinif||o.sinifId===sinif),[ogrenciler,sinif]);
 return <section className="flex flex-col gap-5"><div><h1 className="text-2xl font-extrabold" style={{color:TEXT,fontFamily:"var(--font-baloo)"}}>{brans} Etkinlik Grupları</h1><p className="mt-1 text-sm" style={{color:TEXT_MUTED}}>Grup oluşturun, farklı sınıflardan öğrencileri ekleyin ve saatli çalışma planlayın.</p></div>
 <div className="rounded-3xl p-5" style={{background:BG1,border:`2px solid ${BORDER}`}}><h2 className="font-bold" style={{color:TEXT}}>Yeni etkinlik grubu</h2><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();calistir(()=>etkinlikGrubuEkle(isim))}}><input value={isim} onChange={e=>setIsim(e.target.value)} placeholder="Etkinlik ismi" className="min-w-0 flex-1 rounded-xl px-3 py-2" style={inputStyle}/><button disabled={pending} className="rounded-xl px-4 font-bold" style={{background:MINT,color:MINT_ON}}>Grup aç</button></form></div>
 {gruplar.map(g=><article key={g.id} className="rounded-3xl p-5" style={{background:BG1,border:`2px solid ${BORDER}`}}><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold" style={{color:TEXT}}><Users size={17} color={MINT}/>{g.isim}</h2><button aria-label="Grubu sil" onClick={()=>confirm("Grup ve çalışmaları silinsin mi?")&&calistir(()=>etkinlikGrubuSil(g.id))}><Trash2 size={17} color={BLUSH}/></button></div>
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl p-4" style={{background:BG1_ALT}}><h3 className="text-sm font-bold" style={{color:TEXT}}>Öğrenci ekle</h3><select value={sinif} onChange={e=>setSinif(e.target.value)} className="mt-2 w-full rounded-xl px-3 py-2" style={inputStyle}>{siniflar.map(s=><option key={s.id} value={s.id}>{s.ad}</option>)}</select><div className="mt-2 max-h-52 space-y-1 overflow-y-auto">{filtre.map(o=>{const uye=g.uyeler.some(u=>u.id===o.id);return <button key={o.id} onClick={()=>calistir(()=>etkinlikUyesiDegistir(g.id,o.id,!uye))} className="flex w-full items-center justify-between rounded-xl px-3 py-2 text-left text-sm" style={{color:TEXT,border:`1px solid ${BORDER_STRONG}`}}><span>{o.ad}</span>{uye?<UserMinus size={15} color={BLUSH}/>:<UserPlus size={15} color={MINT}/>}</button>})}</div></div>
  <CalismaForm groupId={g.id} pending={pending} calistir={calistir}/></div></article>)}
 {mesaj&&<p role="alert" style={{color:BLUSH}}>{mesaj}</p>}</section>;
}
function CalismaForm({groupId,pending,calistir}:{groupId:string;pending:boolean;calistir:(f:()=>Promise<{error:string|null}>)=>void}){const [isim,setIsim]=useState(""),[tarih,setTarih]=useState(""),[bas,setBas]=useState(""),[bit,setBit]=useState("");return <form className="rounded-2xl p-4" style={{background:BG1_ALT}} onSubmit={e=>{e.preventDefault();calistir(()=>etkinlikCalismasiEkle({groupId,isim,tarih,baslangicSaat:bas,bitisSaat:bit}))}}><h3 className="flex items-center gap-2 text-sm font-bold" style={{color:TEXT}}><CalendarPlus size={16} color={MINT}/>Çalışma ekle</h3><input value={isim} onChange={e=>setIsim(e.target.value)} placeholder="Çalışma adı" className="mt-2 w-full rounded-xl px-3 py-2" style={inputStyle}/><input type="date" value={tarih} onChange={e=>setTarih(e.target.value)} className="mt-2 w-full rounded-xl px-3 py-2" style={inputStyle}/><div className="mt-2 grid grid-cols-2 gap-2"><input aria-label="Başlangıç" type="time" value={bas} onChange={e=>setBas(e.target.value)} className="rounded-xl px-3 py-2" style={inputStyle}/><input aria-label="Bitiş" type="time" value={bit} onChange={e=>setBit(e.target.value)} className="rounded-xl px-3 py-2" style={inputStyle}/></div><button disabled={pending} className="mt-3 rounded-xl px-4 py-2 font-bold" style={{background:MINT,color:MINT_ON}}>Çalışmayı gönder</button></form>}
function OgrenciEtkinlikleri({atamalar,pending,calistir,mesaj}:{atamalar:EtkinlikAtamasi[];pending:boolean;calistir:(f:()=>Promise<{error:string|null}>)=>void;mesaj:string|null}){const [gerekceler,setGerekceler]=useState<Record<string,string>>({});return <section><h1 className="flex items-center gap-2 text-2xl font-extrabold" style={{color:TEXT}}><Music color={MINT}/>Etkinlikler</h1><div className="mt-4 space-y-3">{atamalar.map(a=><article key={a.id} className="rounded-3xl p-5" style={{background:BG1,border:`2px solid ${BORDER}`}}><p className="text-xs font-bold" style={{color:MINT}}>{a.grupIsmi}</p><h2 className="mt-1 font-bold" style={{color:TEXT}}>{a.etkinlikIsmi}</h2><p className="mt-1 text-sm" style={{color:TEXT_MUTED}}>{a.tarih} · {a.baslangicSaat.slice(0,5)}-{a.bitisSaat.slice(0,5)}</p>{a.durum==="karar_bekliyor"&&<div className="mt-4"><p className="text-sm font-semibold" style={{color:BLUSH}}>Bu çalışma mevcut programınızla çakışıyor.</p><textarea value={gerekceler[a.id]??""} onChange={e=>setGerekceler(x=>({...x,[a.id]:e.target.value}))} placeholder="Reddedecekseniz gerekçenizi yazın" className="mt-2 w-full rounded-xl px-3 py-2" style={inputStyle}/><div className="mt-2 flex flex-wrap gap-2"><button disabled={pending} onClick={()=>calistir(()=>etkinlikKarariVer(a.id,"kaydir"))} className="rounded-xl px-3 py-2 text-sm font-bold" style={{background:MINT,color:MINT_ON}}>Önceki programı kaydır</button><button disabled={pending} onClick={()=>calistir(()=>etkinlikKarariVer(a.id,"reddet",gerekceler[a.id]))} className="rounded-xl px-3 py-2 text-sm font-bold" style={{color:BLUSH,border:`2px solid ${BLUSH}`}}>Reddet</button></div></div>}{a.durum==="kabul"&&<p className="mt-3 text-sm font-bold" style={{color:MINT}}>Programa alındı</p>}{a.durum==="reddedildi"&&<p className="mt-3 text-sm" style={{color:BLUSH}}>Reddedildi: {a.redGerekcesi}</p>}</article>)}{!atamalar.length&&<p style={{color:TEXT_MUTED}}>Henüz etkinlik çalışması yok.</p>}</div>{mesaj&&<p role="alert" className="mt-3" style={{color:BLUSH}}>{mesaj}</p>}</section>}
