"use client";
import {useCallback,useEffect,useState,useTransition,type ReactNode} from "react";
import {Check,Trash2,Trophy,Users} from "lucide-react";
import {etkinlikOkudum,sosyalEtkinlikleriGetir,yarismaEkle,yarismaSil,type AtanabilirOgretmen,type SosyalEtkinlik,type YarismaTuru} from "@/app/dashboard/yarisma-actions";
import {BG0,BG1,BG1_ALT,BORDER,BORDER_STRONG,BLUSH,MINT,MINT_BG,MINT_ON,TEXT,TEXT_MUTED} from "@/lib/theme";
const TURLER:{id:YarismaTuru;ad:string}[]=[{id:"proje",ad:"Proje"},{id:"yarisma",ad:"Yarışma"},{id:"program",ad:"Program"}];
const yaz=(t:string)=>new Date(`${t}T12:00:00`).toLocaleDateString("tr-TR",{day:"numeric",month:"long",year:"numeric"});

export function SosyalEtkinlikler({okumaOnayi=true}:{okumaOnayi?:boolean}){
 const [liste,setListe]=useState<SosyalEtkinlik[]>([]),[ogretmenler,setOgretmenler]=useState<AtanabilirOgretmen[]>([]),[atamaYapabilir,setAtamaYapabilir]=useState(false),[secili,setSecili]=useState<string[]>([]),[mesaj,setMesaj]=useState<string|null>(null),[pending,start]=useTransition();
 const [isim,setIsim]=useState(""),[tur,setTur]=useState<YarismaTuru>("program"),[tarih,setTarih]=useState(""),[son,setSon]=useState("");
 const yukle=useCallback(async()=>{const r=await sosyalEtkinlikleriGetir();setListe(r.etkinlikler);setOgretmenler(r.ogretmenler);setAtamaYapabilir(r.atamaYapabilir);setMesaj(r.error)},[]);
 // Sunucu aksiyonundan gelen ilk kurum/atama görünümünü istemci durumuna aktarır.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void yukle()},[yukle]);
 const calistir=(f:()=>Promise<{error:string|null}>,basari:string)=>start(async()=>{const r=await f();setMesaj(r.error??basari);if(!r.error)await yukle()});
 const sec=(id:string)=>setSecili(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id]);
 return <div className="space-y-5">
  <section className="rounded-3xl p-5" style={{background:BG1,border:`2px solid ${BORDER}`}}><div className="flex items-center gap-2"><Trophy size={19} color={MINT}/><h1 className="text-xl font-extrabold" style={{color:TEXT}}>Sosyal Etkinlikler ve Yarışmalar</h1></div><p className="mt-1 text-sm" style={{color:TEXT_MUTED}}>Bu alan, Beden Eğitimi ve Müzik etkinlik gruplarından bağımsızdır. Yalnız size atanan okul görevleri ajandanıza eklenir.</p></section>
  <section><h2 className="mb-3 text-lg font-extrabold" style={{color:TEXT}}>{okumaOnayi?"Görevleriniz":"Kurum etkinlikleri"}</h2><div className="space-y-3">{liste.map(e=><Karti key={e.id} e={e} pending={pending} onOku={okumaOnayi&&!e.okundu?()=>calistir(()=>etkinlikOkudum(e.id),"Görev ajandanıza eklendi."):undefined} onSil={e.silinebilir?()=>{if(confirm("Bu kayıt silinsin mi?"))calistir(()=>yarismaSil(e.id),"Kayıt silindi.")}:undefined}/>)}{!liste.length&&<p className="rounded-2xl p-4 text-sm" style={{background:BG0,color:TEXT_MUTED}}>Henüz atanmış görev yok.</p>}</div></section>
  <form onSubmit={e=>{e.preventDefault();calistir(()=>yarismaEkle({isim,tur,tarih,sonBasvuruTarihi:son||undefined,teacherIds:secili}),"Etkinlik atandı.");setIsim("");setTarih("");setSon("");setSecili([])}} className="rounded-3xl p-5" style={{background:BG1,border:`2px solid ${BORDER}`}}><h2 className="font-extrabold" style={{color:TEXT}}>Yeni etkinlik ekle</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Alan ad="Etkinlik adı"><input required minLength={2} value={isim} onChange={e=>setIsim(e.target.value)}/></Alan><Alan ad="Etkinlik türü"><select value={tur} onChange={e=>setTur(e.target.value as YarismaTuru)}>{TURLER.map(t=><option key={t.id} value={t.id}>{t.ad}</option>)}</select></Alan><Alan ad="Etkinlik tarihi"><input required type="date" value={tarih} onChange={e=>setTarih(e.target.value)}/></Alan><Alan ad="Son başvuru tarihi (isteğe bağlı)"><input type="date" value={son} onChange={e=>setSon(e.target.value)}/></Alan></div>
   {atamaYapabilir&&<div className="mt-4 rounded-2xl p-3" style={{background:BG0,border:`1px solid ${BORDER}`}}><div className="mb-2 flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-xs font-bold" style={{color:TEXT}}><Users size={14} color={MINT}/>Görevlendirilecek öğretmenler</span><button type="button" onClick={()=>setSecili(secili.length===ogretmenler.length?[]:ogretmenler.map(o=>o.id))} className="text-[11px] font-bold" style={{color:MINT}}>{secili.length===ogretmenler.length?"Seçimi kaldır":"Tümünü seç"}</button></div><div className="grid gap-2 sm:grid-cols-2">{ogretmenler.map(o=><label key={o.id} className="flex cursor-pointer items-center gap-2 rounded-xl p-2.5 text-sm" style={{background:BG1_ALT,color:TEXT,border:`1px solid ${secili.includes(o.id)?MINT:BORDER_STRONG}`}}><input type="checkbox" checked={secili.includes(o.id)} onChange={()=>sec(o.id)}/><span className="min-w-0"><strong>{o.ad}</strong><span className="block truncate text-[10px]" style={{color:TEXT_MUTED}}>{o.brans}</span></span></label>)}</div>{!ogretmenler.length&&<p className="text-xs" style={{color:TEXT_MUTED}}>Atanabilecek öğretmen bulunamadı.</p>}</div>}
   <button disabled={pending||(atamaYapabilir&&!secili.length)} className="mt-4 rounded-full px-5 py-2 text-sm font-bold disabled:opacity-60" style={{background:MINT,color:MINT_ON}}>{pending?"Kaydediliyor...":atamaYapabilir?"Seçilen öğretmenlere ata":"Etkinliği ekle"}</button></form>{mesaj&&<p role="status" className="text-sm font-semibold" style={{color:mesaj.toLocaleLowerCase("tr").includes("hata")?BLUSH:MINT}}>{mesaj}</p>}
 </div>}
function Alan({ad,children}:{ad:string;children:ReactNode}){return <label className="flex flex-col gap-1"><span className="text-xs font-bold" style={{color:TEXT_MUTED}}>{ad}</span><div className="[&_input]:w-full [&_select]:w-full [&_input]:rounded-xl [&_select]:rounded-xl [&_input]:border-2 [&_select]:border-2 [&_input]:px-3 [&_select]:px-3 [&_input]:py-2.5 [&_select]:py-2.5 [&_input]:text-sm [&_select]:text-sm [&_input]:outline-none [&_select]:outline-none" style={{color:TEXT}}>{children}</div></label>}
function Karti({e,pending,onOku,onSil}:{e:SosyalEtkinlik;pending:boolean;onOku?:()=>void;onSil?:()=>void}){return <article className="rounded-2xl p-4" style={{background:BG1_ALT,border:`1px solid ${BORDER}`,opacity:e.aktif?1:.62}}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-wide" style={{color:MINT}}>{e.tur==="yarisma"?"Yarışma":e.tur==="proje"?"Proje":"Program"}</div><h3 className="font-bold" style={{color:TEXT}}>{e.isim}</h3><p className="mt-1 text-xs" style={{color:TEXT_MUTED}}>{yaz(e.tarih)}{e.sonBasvuruTarihi?` · Son başvuru: ${yaz(e.sonBasvuruTarihi)}`:""} · {e.ekleyenAd}{!e.aktif?" · Tarihi geçti":""}</p>{e.atananlar.length>0&&<p className="mt-1 text-[11px]" style={{color:TEXT_MUTED}}>Atananlar: {e.atananlar.join(", ")}</p>}</div><div className="flex gap-2">{e.okundu&&<span className="flex items-center gap-1 rounded-full px-3 py-1.5 text-xs font-bold" style={{background:MINT_BG,color:MINT}}><Check size={13}/>Ajandada</span>}{onOku&&<button disabled={pending} onClick={onOku} className="rounded-full px-3 py-1.5 text-xs font-bold" style={{background:MINT,color:MINT_ON}}>Okudum</button>}{onSil&&<button disabled={pending} aria-label="Sil" onClick={onSil} className="grid h-8 w-8 place-items-center rounded-full" style={{border:`1px solid ${BORDER_STRONG}`}}><Trash2 size={14} color={BLUSH}/></button>}</div></div></article>}
