"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {etkinlikBransiMi} from "@/lib/etkinlik";

async function kullanici(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");return{supabase,user,admin:createAdminClient()};}
async function etkinlikOgretmeni(){const k=await kullanici();const{data:t}=await k.admin.from("teachers").select("school_id,brans,profiles!teachers_id_fkey(role),schools!teachers_school_id_fkey(tur)").eq("id",k.user.id).single();const rol=(t?.profiles as unknown as {role:string}|null)?.role,kurum=(t?.schools as unknown as {tur:string}|null)?.tur;if(!t||rol!=="ogretmen"||kurum!=="okul"||!etkinlikBransiMi(t.brans))return{...k,error:"Bu bölüm yalnızca okullardaki Beden Eğitimi ve Müzik öğretmenlerine açıktır.",teacher:null};return{...k,error:null,teacher:t};}
const yenile=()=>revalidatePath("/dashboard/etkinlikler");

export async function etkinlikGrubuEkle(isim:string){const k=await etkinlikOgretmeni();if(k.error||!k.teacher)return{error:k.error};isim=isim.trim();if(isim.length<2||isim.length>100)return{error:"Etkinlik adı 2-100 karakter olmalıdır."};const{error}=await k.admin.from("etkinlik_gruplari").insert({teacher_id:k.user.id,school_id:k.teacher.school_id,isim});yenile();return{error:error?.message??null};}
export async function etkinlikGrubuSil(id:string){const k=await etkinlikOgretmeni();if(k.error)return{error:k.error};const{error}=await k.admin.from("etkinlik_gruplari").delete().eq("id",id).eq("teacher_id",k.user.id);yenile();return{error:error?.message??null};}
export async function etkinlikUyesiDegistir(groupId:string,studentId:string,ekle:boolean){const k=await etkinlikOgretmeni();if(k.error||!k.teacher)return{error:k.error};const{data:g}=await k.admin.from("etkinlik_gruplari").select("id").eq("id",groupId).eq("teacher_id",k.user.id).maybeSingle();const{data:s}=await k.admin.from("students").select("id").eq("id",studentId).eq("school_id",k.teacher.school_id).maybeSingle();if(!g||!s)return{error:"Grup veya öğrenci bu kuruma ait değil."};const q=ekle?await k.admin.from("etkinlik_grup_uyeleri").upsert({group_id:groupId,student_id:studentId}):await k.admin.from("etkinlik_grup_uyeleri").delete().eq("group_id",groupId).eq("student_id",studentId);yenile();return{error:q.error?.message??null};}

export async function etkinlikCalismasiEkle(input:{groupId:string;isim:string;tarih:string;baslangicSaat:string;bitisSaat:string}){const k=await etkinlikOgretmeni();if(k.error||!k.teacher)return{error:k.error};const isim=input.isim.trim();if(isim.length<2||isim.length>150)return{error:"Çalışma adı 2-150 karakter olmalıdır."};if(!/^\d{4}-\d{2}-\d{2}$/.test(input.tarih)||!/^\d{2}:\d{2}$/.test(input.baslangicSaat)||!/^\d{2}:\d{2}$/.test(input.bitisSaat)||input.bitisSaat<=input.baslangicSaat)return{error:"Geçerli bir tarih ve saat aralığı girin."};
 const{data:g}=await k.admin.from("etkinlik_gruplari").select("id,isim").eq("id",input.groupId).eq("teacher_id",k.user.id).maybeSingle();if(!g)return{error:"Grup bulunamadı."};const{data:uyeler}=await k.admin.from("etkinlik_grup_uyeleri").select("student_id").eq("group_id",g.id);if(!uyeler?.length)return{error:"Çalışma eklemek için grupta öğrenci olmalı."};
 const{data:c,error}=await k.admin.from("etkinlik_calismalari").insert({group_id:g.id,isim,tarih:input.tarih,baslangic_saat:input.baslangicSaat,bitis_saat:input.bitisSaat}).select("id").single();if(error||!c)return{error:error?.message??"Çalışma eklenemedi."};
 const atamalar=[] as {calisma_id:string;student_id:string;durum:string;cakisiyor:boolean}[];for(const u of uyeler){const{count:p}=await k.admin.from("gorev_atamalari").select("id",{count:"exact",head:true}).eq("student_id",u.student_id).eq("programa_eklendi_mi",true).eq("ogrenci_tarih",input.tarih).lt("ogrenci_baslangic_saat",input.bitisSaat).gt("ogrenci_bitis_saat",input.baslangicSaat);const{count:e}=await k.admin.from("etkinlik_calisma_atamalari").select("id,etkinlik_calismalari!inner(tarih,baslangic_saat,bitis_saat)",{count:"exact",head:true}).eq("student_id",u.student_id).eq("durum","kabul").eq("etkinlik_calismalari.tarih",input.tarih).lt("etkinlik_calismalari.baslangic_saat",input.bitisSaat).gt("etkinlik_calismalari.bitis_saat",input.baslangicSaat);const cak=!!p||!!e;atamalar.push({calisma_id:c.id,student_id:u.student_id,durum:cak?"karar_bekliyor":"kabul",cakisiyor:cak});}
 const a=await k.admin.from("etkinlik_calisma_atamalari").insert(atamalar);if(a.error)return{error:a.error.message};await k.admin.from("bildirimler").insert(uyeler.map(u=>({profile_id:u.student_id,tur:"sistem",baslik:`${g.isim}: yeni çalışma`,mesaj:`${isim} · ${input.tarih} ${input.baslangicSaat}-${input.bitisSaat}${atamalar.find(x=>x.student_id===u.student_id)?.cakisiyor?" · Programınızla çakışıyor; Etkinlikler bölümünden karar verin.":""}`})));yenile();return{error:null};}

function dakika(s:string){const[a,b]=s.slice(0,5).split(":").map(Number);return a*60+b}function saat(d:number){return`${String(Math.floor(d/60)).padStart(2,"0")}:${String(d%60).padStart(2,"0")}:00`}
export async function etkinlikKarariVer(atamaId:string,karar:"kabul"|"kaydir"|"reddet",gerekce?:string){const k=await kullanici();const{data:a}=await k.admin.from("etkinlik_calisma_atamalari").select("id,student_id,durum,cakisiyor,calisma_id,etkinlik_calismalari(id,isim,tarih,baslangic_saat,bitis_saat,etkinlik_gruplari(teacher_id,isim))").eq("id",atamaId).eq("student_id",k.user.id).maybeSingle();if(!a||a.durum!=="karar_bekliyor")return{error:"Bekleyen etkinlik kararı bulunamadı."};const c=a.etkinlik_calismalari as unknown as {isim:string;tarih:string;baslangic_saat:string;bitis_saat:string;etkinlik_gruplari:{teacher_id:string;isim:string}};
 if(karar==="reddet"){const g=(gerekce??"").trim();if(g.length<3||g.length>500)return{error:"Red gerekçesi 3-500 karakter olmalıdır."};const{data:ogrenci}=await k.admin.from("profiles").select("ad").eq("id",k.user.id).maybeSingle();await k.admin.from("etkinlik_calisma_atamalari").update({durum:"reddedildi",red_gerekcesi:g,karar_at:new Date().toISOString()}).eq("id",a.id);await k.admin.from("bildirimler").insert({profile_id:c.etkinlik_gruplari.teacher_id,tur:"sistem",baslik:`Etkinlik reddedildi: ${c.etkinlik_gruplari.isim}`,mesaj:`${ogrenci?.ad??"Öğrenci"}, ${c.isim} çalışmasını reddetti. Gerekçe: ${g}`});yenile();return{error:null};}
 if(a.cakisiyor&&karar!=="kaydir")return{error:"Çakışan program için önceki programı kaydır seçeneğini kullanın veya reddedin."};
 if(karar==="kaydir"){const{data:planlar}=await k.admin.from("gorev_atamalari").select("id,ogrenci_baslangic_saat,ogrenci_bitis_saat").eq("student_id",k.user.id).eq("programa_eklendi_mi",true).eq("ogrenci_tarih",c.tarih).lt("ogrenci_baslangic_saat",c.bitis_saat).gt("ogrenci_bitis_saat",c.baslangic_saat).order("ogrenci_baslangic_saat");let imlec=dakika(c.bitis_saat);for(const p of planlar??[]){const sure=dakika(p.ogrenci_bitis_saat)-dakika(p.ogrenci_baslangic_saat);if(imlec+sure>1440)return{error:"Önceki program gün sonrasına taşacağı için kaydırılamadı. Etkinliği reddedin veya öğretmeninizle görüşün."};await k.admin.from("gorev_atamalari").update({ogrenci_baslangic_saat:saat(imlec),ogrenci_bitis_saat:saat(imlec+sure)}).eq("id",p.id).eq("student_id",k.user.id);imlec+=sure;}}
 await k.admin.from("etkinlik_calisma_atamalari").update({durum:"kabul",karar_at:new Date().toISOString()}).eq("id",a.id);yenile();return{error:null};}
